spring:
  application:
    name: SERVICE-REGISTRY
  cloud:
    loadbalancer:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true
server:
  port: 8761